### ISSUE TITLE
Not able to generate the bna file

### ISSUE THREAD

**Issue by ragdeshp** [IBM/Blockchain_for_TelcoRoaming#3]
Following are the versions installed in my environment.
node version - v8.4.0
python version - 2.7.10
composer - v0.19.5
But unable to create bna file with npm install

**Comment by amanrubalibm** [comment]
Composer version is correct
The node version used was node version is v9.10.1
Please check if this works.
The other way around could be just using the code from javascript, model and query files in your composer playground.

**Comment by ljbennett62** [comment]
@amanrubalibm - we are upgrading this to IBM Blockchain Platform
