### ISSUE TITLE
npm install problem

### ISSUE THREAD

**Issue by Arucald** [IBM/Blockchain_for_TelcoRoaming#6]
Hi, I'm a new developer of blockchain.
When I run the npm install in the "Generate the Business Network Archive (BNA)" process, it shows:
---------------------------------------------
In file included from ../src/hashtable.cpp:1:
../src/hashtable.h:7:10: fatal error: 'tr1/unordered_map' file not found
#include <tr1/unordered_map>
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/native/src/hashtable.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/dada/.nvm/versions/node/v8.15.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/Users/dada/.nvm/versions/node/v8.15.0/bin/node" "/Users/dada/.nvm/versions/node/v8.15.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /Users/dada/Blockchain_for_TelcoRoaming-master/node_modules/hashtable
gyp ERR! node -v v8.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hashtable@2.0.2 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hashtable@2.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dada/.npm/_logs/2019-01-16T09_23_16_524Z-debug.log 
--------------------------------------------------------------------------------
Is there something wrong with nvm or nodejs?  Hope anyone can guide me to solve the problem.

**Comment by ljbennett62** [comment]
@Arucald - we are upgrading this to IBM Blockchain Platform
